package com.meiqi.openservice.action.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-11T14:19:44.687+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "HomeLikeSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HomeLikeSoap {

    @WebResult(name = "sendSmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://tempuri.org/", className = "com.meiqi.openservice.action.webservice.client.demo.SendSms")
    @WebMethod(action = "http://tempuri.org/sendSms")
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://tempuri.org/", className = "com.meiqi.openservice.action.webservice.client.demo.SendSmsResponse")
    public boolean sendSms(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "ExtNO", targetNamespace = "http://tempuri.org/")
        java.lang.String extNO
    );
}
